=== sanjaayanand/Student-Attendeance-Management-System/newXmlSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="student">
 <xs:complexType>
 
 <xs:sequence>
 <xs:element name="stu" maxOccurs="unbounded">
 <xs:complexType>
 <xs:sequence>
 <xs:element name="id" type="xs:integer"/>
 <xs:element name="name" type="xs:string"/>
 <xs:element name="department" type="xs:string"/>
 <xs:element name="email" type="xs:string"/>
 <xs:element name="mobileNumber" type="xs:integer"/>
 </xs:sequence>
 <xs:attribute name="stuid" type="xs:string" use="required"/>
 </xs:complexType>
 </xs:element>
 </xs:sequence>

 </xs:complexType> 
</xs:element> 
</xs:schema>

=== sanjaayanand/Student-Attendeance-Management-System/wdtest.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="student.xsl" type="text/xsl"?>
<student
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="newXmlSchema.xsd">
 <stu stuid="id_1">
 <id>001</id>
 <name>sam</name>
 <department>MCA</department>
 <email>sam@gmail.com</email>
 <mobileNumber>9654213252</mobileNumber>
 
 </stu>

 <stu stuid="id_2">
 	<id>002</id>
 <name>Mala</name>
 <department>MCA</department>
 <email>mala@gmail.com</email>
 <mobileNumber>965412582</mobileNumber>
 
 </stu>

 <stu stuid="id_3">
 	<id>003</id>
 <name>bala</name>
 <department>MCA</department>
 <email>bala@gmail.com</email>
 <mobileNumber>9548754122</mobileNumber> 
 </stu>

 <stu stuid="id_4">
 	<id>004</id>
 <name>guru</name>
 <department>MCA</department>
 <email>guru@gmail.com</email>
 <mobileNumber>9874561230</mobileNumber> 
 </stu>

 <stu stuid="id_5">
 	<id>005</id>
 <name>aniq</name>
 <department>MCA</department>
 <email>aniq@gmail.com</email>
 <mobileNumber>9784512421</mobileNumber> 
 </stu>
</student>
